resources:
- name: Fetch-Git
  type: git
  source:
    uri: https://github.com/reagul/flight-school
    branch: master

jobs:
- name: TestApp
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/build.yml
